version: '3'

services:
  database:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "drilling_dev"
    networks:
      backend:
        aliases:
          - "database"

networks:
  backend:
    driver: bridge